name: Doge_Value
on: [pull_request, workflow_dispatch]
jobs:
  check-build:
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.4'
      - run: |
          python -m pip install --upgrade pip
          pip install bs4
      - run: python Doge_Value.py
      
